name: Build Nextcloud Image Latest

on:
  push:
    branches:
      - "!*"
    tags:
      - '*'
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\///}" >> $GITHUB_ENV
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: brabhamm/nextcloud:${{ env.TAG }}
